# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python


trigger:
- master

pool:
  vmImage: ubuntu-20.04.6

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.12'
    addToPath: true
    architecture: 'x64'


- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      print('Hello world 1')
      print('Hello world 2')
    

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

#- task: JavaToolInstaller@0
#  displayName: 'Use Java 11'
#  inputs:
#    versionSpec: 11
#    jdkArchitectureOption: x64
#    jdkSourceOption: PreInstalled

- script: |
    rmdir -f /home/vsts/work/
  displayName: 'Clear Agent Cache'

- task: FortifyOnDemandStatic@8
  inputs:
    FortifyProjects: '/home/vsts/work/_temp/'
    FodConnection: 'ams test sso test tenant'
    ReleaseOptions: '0'
    ReleaseId: 397851
    EntitlementSelection: '1'
    EntitlementPreference: '1'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '0'
    BuildType: 'python'
    PollingInterval: 0
    PolicyFailAction: '0'
